LIGAS = {
    "La Liga (España)": "https://www.livefutbol.com/competition/co97/espana-primera-division/all-matches/",
    "Bundesliga (Alemania)": "https://www.livefutbol.com/competition/co12/alemania-bundesliga/all-matches/",
    "Premier League (Inglaterra)": "https://www.livefutbol.com/competition/co91/inglaterra-premier-league/all-matches/",
    "Ligue 1 (Francia)": "https://www.livefutbol.com/competition/co71/francia-ligue-1/all-matches/",
    "Serie A (Italia)": "https://www.livefutbol.com/competition/co111/italia-serie-a/all-matches/",
    "Segunda División (España)": "https://www.livefutbol.com/competition/co110/espana-segunda-division/all-matches/",
    "Primera División Femenina (España)": "https://www.livefutbol.com/competition/co2737/espana-mujeres-primera-division/all-matches/",
    "Primera Federación G1 (España)": "https://www.livefutbol.com/competition/co6373/espana-primera-federacion-grupo-1/all-matches/",
    "Primera Federación G2 (España)": "https://www.livefutbol.com/competition/co6515/espana-primera-federacion-grupo-2/all-matches/",
    "Primera A (Colombia)": "https://www.livefutbol.com/competition/co25/colombia-primera-a/all-matches/",
    "Primeira Liga (Portugal)": "https://www.livefutbol.com/competition/co123/portugal-primeira-liga/all-matches/",
    "2. Bundesliga (Alemania)": "https://www.livefutbol.com/competition/co3/alemania-2-bundesliga/all-matches/",
    "Championship (Inglaterra)": "https://www.livefutbol.com/competition/co20/inglaterra-championship/all-matches/",
    "Ligue 2 (Francia)": "https://www.livefutbol.com/competition/co72/francia-ligue-2/all-matches/",
    "Serie B (Italia)": "https://www.livefutbol.com/competition/co113/italia-serie-b/all-matches/",
    "Eredivisie (Países Bajos)": "https://www.livefutbol.com/competition/co37/paises-bajos-eredivisie/all-matches/",
    "Pro League (Bélgica)": "https://www.livefutbol.com/competition/co49/belgica-pro-league/all-matches/",
    "Super League (Grecia)": "https://www.livefutbol.com/competition/co122/grecia-super-league/all-matches/",
    "Super League (Suiza)": "https://www.livefutbol.com/competition/co115/suiza-super-league/all-matches/",
    "SüperLig (Turquía)": "https://www.livefutbol.com/competition/co116/turquia-sueperlig/all-matches/",
    "Premier Liga (Rusia)": "https://www.livefutbol.com/competition/co95/rusia-premier-liga/all-matches/",
    "Saudi Pro League (Arabia Saudita)": "https://www.livefutbol.com/competition/co1169/arabia-saudita-saudi-pro-league/all-matches/",
    "División Profesional (Bolivia)": "https://www.livefutbol.com/competition/co1103/bolivia-division-profesional/all-matches/",
    "Parva Liga (Bulgaria)": "https://www.livefutbol.com/competition/co138/bulgaria-parva-liga/all-matches/",
    "Segunda Federación G1 (España)": "https://www.livefutbol.com/competition/co6508/espana-segunda-federacion-grupo-1/all-matches/",
    "Segunda Federación G2 (España)": "https://www.livefutbol.com/competition/co6510/espana-segunda-federacion-grupo-2/all-matches/",
    "Segunda Federación G3 (España)": "https://www.livefutbol.com/competition/co6511/espana-segunda-federacion-grupo-3/all-matches/",
    "Segunda Federación G4 (España)": "https://www.livefutbol.com/competition/co6512/espana-segunda-federacion-grupo-4/all-matches/",
    "Segunda Federación G5 (España)": "https://www.livefutbol.com/competition/co6514/espana-segunda-federacion-grupo-5/all-matches/"
}
